### ISSUE TITLE
Nonfunctional since V10 update

### ISSUE THREAD

**Issue by Dntfdtrols** [Lavaeolous/PF1-StatBlock-Converter-Module#549] opened 2022-09-02 11:51 UTC
Parses only up to statistics. Throws normal error codes if you take out the statistics part but stays on "parsing: base" if statistics are included. This mod is literally my favorite and I might just have to go back to roll20 without it. Please fix it <3

**Comment by gregprater311** [comment] 2022-09-11 12:17
Curious as to the future of this very useful module.

**Comment by ElvesLie** [comment] 2022-09-12 15:09
I've been having this issue too. I updated Foundry and am desperately trying to work on my campaign but am now stuck with so much progress at a sudden halt. Can we expect an update any time soon? Thanks

**Comment by Eagle0600** [comment] 2022-09-12 21:10
As a temporary solution, you could download statblock-converter/scripts/sbcUtils.js from my commit (above) and place it in Documents/FoundryVTT/Data/modules/pf1-statblock-converter/scripts.

**Comment by ElvesLie** [comment] 2022-09-13 04:14
For me the location was in `C:\Users\%username%\AppData\Local\FoundryVTT\Data\modules\pf1-statblock-converter\scripts`.

I've replaced the file but without any significant changes (I did try disabling every other module to test this as well). 

As you can see with the image below, I am using your version, and for reference I'm using Version 10, Build 285 of Foundry.

![FoundryPullRequest](https://user-images.githubusercontent.com/66757457/189805830-1c1c59d3-2f92-4dd9-b0cf-4bf468940d7c.png)

Thanks for your help on this matter! :)

**Comment by TheQuain** [comment] 2022-09-13 04:39
You can right-click the taskbar icon for foundry when it's open and select "Browse User Data" to get to it wherever it is installed. 

I'm working on fixing this for myself, I've been out of coding for years and want to practice a little bit. So if nobody else posts a fix before I get it working reasonably I will. (non-item attacks and multiple class-level characters are importing borked still for me as of current)

**Comment by Eagle0600** [comment] 2022-09-13 06:05
@ElvesLie, can you please tell me which creature you are trying to import? Perhaps I can replicate your error and have a go at it myself

**Comment by ElvesLie** [comment] 2022-09-13 07:20
I've been trying random ones like `Recruit (warrior 1)` from the NPC Codex for example.

I feel like there's a 50/50 chance I've missed a critical step here, but to my current knowledge, it should be working after implanting your fix. Thanks for taking the time to reach out!

**Comment by ElvesLie** [comment] 2022-09-13 07:25
> You can right-click the taskbar icon for foundry when it's open and select "Browse User Data" to get to it wherever it is installed.
> 
> I'm working on fixing this for myself, I've been out of coding for years and want to practice a little bit. So if nobody else posts a fix before I get it working reasonably I will. (non-item attacks and multiple class-level characters are importing borked still for me as of current)

I'm very rusty myself, haha. I tried having a little peek myself before giving up and just coming to GitHub for more answers. Yeah my **Browse User Data** takes me to the AppData/Local area, which is where I've put the .js in. `C:\Users\%userdata%\AppData\Local\FoundryVTT\Data\modules\pf1-statblock-converter\scripts`

I know that name has been changed to id and other various things, but kept looking in the wrong place to fix it. I'm tired and just too out of practice to bother too much into it anymore.

**Comment by Eagle0600** [comment] 2022-09-13 11:41
@ElvesLie
Check that you are using build 0.82.1 of PF1 system. Try creating a new world with statblock converter as the only loaded module. Import using the following text exactly. If it doesn't work, reload and open up the DevTools (F12). Go to the console, right click, and clear console. Open the converter and try again. When it fails, copy the red text for me.
```
Recruit CR 1/3
Source NPC Codex pg. 266
XP 135
Dwarf warrior 1
N Medium humanoid (dwarf)
Init +0; Senses darkvision 60 ft.; Perception +1
Defense
AC 18, touch 10, flat-footed 18 (+6 armor, +2 shield)
hp 8 (1d10+3)
Fort +4, Ref +0, Will +0; +2 vs. poison, spells, and spell-like abilities
Defensive Abilities defensive training (+4 dodge bonus to AC vs. giants)
Offense
Speed 20 ft.
Melee dwarven waraxe +3 (1d10+1/×3) or dagger +2 (1d4+1/19–20)
Ranged light crossbow +1 (1d8/19–20)
Special Attacks +1 on attack rolls against goblinoid and orc humanoids
Tactics
During Combat The warrior prefers melee combat and working with other soldiers. He uses alchemist’s fire against targets resistant to weapon damage.
Statistics
Str 13, Dex 11, Con 14, Int 10, Wis 10, Cha 7
Base Atk +1; CMB +2; CMD 12 (16 vs. bull rush or trip)
Feats Weapon Focus (dwarven waraxe)
Skills Intimidate +2, Perception +1 (+3 to notice unusual stonework)
Languages Common, Dwarven
Combat Gear alchemist’s fire; Other Gear chainmail, heavy wooden shield, dagger, dwarven waraxe, light crossbow with 20 bolts, 12 gp
```

**Comment by ElvesLie** [comment] 2022-09-13 11:48
> @ElvesLie Check that you are using build 0.82.1 of PF1 system. Try creating a new world with statblock converter as the only loaded module. Import using the following text exactly. If it doesn't work, reload and open up the DevTools (F12). Go to the console, right click, and clear console. Open the converter and try again. When it fails, copy the red text for me.
> 
> ```
> Recruit CR 1/3
> Source NPC Codex pg. 266
> XP 135
> Dwarf warrior 1
> N Medium humanoid (dwarf)
> Init +0; Senses darkvision 60 ft.; Perception +1
> Defense
> AC 18, touch 10, flat-footed 18 (+6 armor, +2 shield)
> hp 8 (1d10+3)
> Fort +4, Ref +0, Will +0; +2 vs. poison, spells, and spell-like abilities
> Defensive Abilities defensive training (+4 dodge bonus to AC vs. giants)
> Offense
> Speed 20 ft.
> Melee dwarven waraxe +3 (1d10+1/×3) or dagger +2 (1d4+1/19–20)
> Ranged light crossbow +1 (1d8/19–20)
> Special Attacks +1 on attack rolls against goblinoid and orc humanoids
> Tactics
> During Combat The warrior prefers melee combat and working with other soldiers. He uses alchemist’s fire against targets resistant to weapon damage.
> Statistics
> Str 13, Dex 11, Con 14, Int 10, Wis 10, Cha 7
> Base Atk +1; CMB +2; CMD 12 (16 vs. bull rush or trip)
> Feats Weapon Focus (dwarven waraxe)
> Skills Intimidate +2, Perception +1 (+3 to notice unusual stonework)
> Languages Common, Dwarven
> Combat Gear alchemist’s fire; Other Gear chainmail, heavy wooden shield, dagger, dwarven waraxe, light crossbow with 20 bolts, 12 gp
> ```

That worked! Thanks for that!

However, I should point out that wasn't the only way to convert a statblock into an actor. If you open the statblock there's also a conversion button there too (which is the button I was referring to). But this is a fine work around for now. You're awesome!

**Comment by Lavaeolous** [comment] 2022-09-13 17:51
Yeah, sbcs not compatible to v10 yet. I plan to work on it in the coming weeks, but have little time currently (and i fear i have to change alot as the data/document structure changed again with v10).

**Comment by multiplenerdgasms** [comment] 2022-09-17 21:56
> Yeah, sbcs not compatible to v10 yet. I plan to work on it in the coming weeks, but have little time currently (and i fear i have to change alot as the data/document structure changed again with v10).

Love your work, mate! Let us know if there is any way we can support you in the task.

**Comment by Lavaeolous** [comment] 2022-09-24 08:52
findEntityInCompendium changed on the systemside. The issue is fixed in the v4.0.0 branch. Most of everything works now, but i still have to test spellcasters

**Comment by gregprater311** [comment] 2022-09-24 16:07
thanks

**Comment by Lavaeolous** [comment] 2022-09-26 08:39
v4.0.0 is now released and should be compatible to v10 of Foundry

**Closed by Lavaeolous** 2022-09-26 08:39 UTC
