### ISSUE TITLE
Attacks with "1dX plus X, X" cause issue

### ISSUE THREAD

**Issue by baileymh** [Lavaeolous/PF1-StatBlock-Converter-Module#468] opened 2021-06-22 03:25 UTC
Two potential issues resulting in hanging on Offense. 

1. `bite +6 (1d6+3 plus disease, paralysis)` seems to cause an issue until replaced with `bite +6 (1d6+3 plus disease and paralysis)`

2. `D domain spell;` label on some statblocks seems to also cause issues with Offensive parsing. Unclear if it also has difficulty with `Domains Chaos, Knowledge`

Example Statblock
```
Ilzek And Jadiss
CR 4
XP 1,200
Ghoul cleric of Kabriri 3 (Pathfinder RPG Bestiary 146)
CE Medium undead
Init +7; Senses darkvision 60 ft.; Perception +10

DEFENSE
AC 19, touch 13, flat-footed 16 (+4 armor, +3 Dex, +2 natural)
hp 37 (5d8+15)
Fort +6, Ref +6, Will +12
Defensive Abilities channel resistance +2; Immune undead traits

OFFENSE
Spd 30 ft.
Melee flail +8 (1d8+5), bite +6 (1d6+3 **_plus disease, paralysis_**), claws +6 (1d4+3 plus paralysis),
Space 5 ft.; Reach 5 ft.
Special Attacks channel negative energy 6/day (DC 14, 2d6), disease (DC 14), paralysis (DC 14)

Spell-Like Abilities (CL 3rd; concentration +7)
At Will—lore keeper
7/day—touch of chaos

Spells Prepared (CL 3rd; concentration +7)
2nd—cure moderate wounds, detect thoughtsD (DC 16), spiritual weapon
1st—cure light wounds, divine favor, protection from lawD, sanctuary (DC 15)
0 (at will)—bleed (DC 14), detect magic, guidance, resistance

**_D domain spell;_** Domains Chaos, Knowledge

TACTICS
During Combat The ghouls use their scrolls of summon monster V to each summon a babau and then cast protection from law in the first 2 rounds of combat while they let the other ghouls engage the PCs in melee. They then cast spiritual weapon, following that up with channeled negative energy before casting divine favor and stepping in to melee. The ghouls keep a few cure spells prepared to cast on Nulkineth, should he require their aid.

Morale The ghouls retreat to Nulkineth's side to protect him if reduced to fewer than 15 hit points.

STATISTICS
Str 17, Dex 17, Con -, Int 13, Wis 18, Cha 16
Base Atk +3; CMB +6; CMD 19
Feats Improved Initiative, Multiattack, Selective Channeling
Skills Acrobatics +6, Bluff +6, Disguise +9, Knowledge (planes) +5, Knowledge (religion) +7, Linguistics +7, Perception +10, Stealth +9
Languages Abyssal, Common, Hallit, Necril
Combat Gear scroll of summon monster V; Other Gear +1 studded leather, flail, 92 gp
``

**Comment by Lavaeolous** [comment] 2021-07-08 08:39
Number 1 is fixed in 3.3.1.

I could not reproduce Number 2, feel free to open a separate issue if this persists for you.

**Closed by Lavaeolous** 2021-07-08 08:39 UTC
Labels: bug
