### ISSUE TITLE
Error when Special Movement is separated by "," instead of ";"

### ISSUE THREAD

**Issue by bmos** [Lavaeolous/PF1-StatBlock-Converter-Module#317] opened 2020-10-26 02:51 UTC
Trying to import this NPC
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Krampus

I get the error

> TypeError: Cannot read property '0' of null

I am, however, able to import this NPC
https://www.aonprd.com/MonsterDisplay.aspx?ItemName=Badger

Foundry 0.7.5
Pathfinder 1 0.75.6
Statblock importer 2.0.5
Windows 10 64-bit

**Comment by classicrp** [comment] 2020-10-26 04:23
It has to do with how you are bringing in your craft, knowledge, perform, etc. skills.  In Krampus's case he's "Knowledge (geography, nobility)" instead of two separate entries.
Hope this helps.

**Comment by classicrp** [comment] 2020-10-26 04:29
Sorry, that was my knee jerk reaction to the statblock.  I've had a bugger of a time over the years with MapTool and HeroLab until I found a small utility "HL2MT.exe" that created an external .token that could be imported into the game.  That tool just dumped whatever was available from HeroLab without all the heavy checking (and having to data duplicate your matches---why I had to put various entries in three .js files for Assassin).
Anyway, I'm retired from the real stuff now so have way more time to tinker... Hope you don't mind.  I'm trying to get my own Game up and running.  AND the PF1 dataset is now coming across locked so I can't get in to monkey with the classes, feats, items etc. anymore.
More ranting. 
Cheers!

**Comment by Lavaeolous** [comment] 2020-10-26 08:58
Hey, Knowledge Skills already get separated if they are noted as "Knowledge (Subskill 1, Subskill2)".

The error in this statblock lies in the special speed after the land/base speed. Normaly thats separated by a semicolon, whereas here its a comma.

I thought i already fixed that, but it seems i have to take another look.
For now, just change

`Speed 60 ft., air walk`

to

`Speed 60 ft.; air walk`

**Comment by bmos** [comment] 2020-10-26 10:36
Thanks both of you!
That movement issue was indeed the issue.

**Comment by Lavaeolous** [comment] 2020-10-28 19:00
Duplicate of #309, fixed in 2.0.7

**Closed by Lavaeolous** 2020-10-28 19:00 UTC
